CODE_OF_CONDUCT.md, CONTRIBUTING.md
Closes: https://github.com/nodejs/gyp-next/issues/12
=> doc: add minimal governance files

pylib/gyp/MSVSProject.py, pylib/gyp/MSVSToolFile.py, pylib/gyp/MSVSUserFile.py, pylib/gyp/MSVSVersion.py, pylib/gyp/generator/analyzer.py, pylib/gyp/generator/dump_dependency_json.py, pylib/gyp/generator/gypd.py, pylib/gyp/generator/make.py, pylib/gyp/generator/msvs.py, pylib/gyp/generator/ninja.py, pylib/gyp/input.py, pylib/gyp/input_test.py, pylib/gyp/ninja_syntax.py, pylib/gyp/xcode_emulation.py, test_gyp.py
Reported by `python -m flake8 . --select F401`
=> chore: remove unused imports

gyp_main.py, pylib/gyp/__init__.py, pylib/gyp/common.py, pylib/gyp/generator/analyzer.py, pylib/gyp/generator/android.py, pylib/gyp/generator/eclipse.py, pylib/gyp/generator/gypd.py, pylib/gyp/generator/make.py, pylib/gyp/generator/msvs.py, pylib/gyp/generator/ninja.py, pylib/gyp/generator/xcode.py, pylib/gyp/input.py, pylib/gyp/xcode_emulation.py, pylib/gyp/xcodeproj_file.py
- E302 expected 2 blank lines, found 1
- E711 comparison to None should be 'if cond is not None:'
- E713 test for membership should be 'not in'
- E721 do not compare types, use 'isinstance()'
- E731 do not assign a lambda expression, use a def
- E741 ambiguous variable name
- F402 import shadowed by loop variable
=> chore: fix a bunch of PEP 8 issues

pylib/gyp/__init__.py, pylib/gyp/easy_xml.py, pylib/gyp/generator/ninja.py, pylib/gyp/generator/xcode.py, pylib/gyp/mac_tool.py
`python -m flake8 . --select E722`
=> chore: do not use bare 'except'

pylib/gyp/generator/compile_commands_json.py
Add default fallback output directory.
/cc @targos
=> fix: compile_commands.json generation

pylib/gyp/generator/analyzer.py, pylib/gyp/generator/android.py, pylib/gyp/generator/compile_commands_json.py, pylib/gyp/generator/dump_dependency_json.py, pylib/gyp/generator/eclipse.py, pylib/gyp/generator/msvs.py, pylib/gyp/input.py, pylib/gyp/xcode_emulation.py, pylib/gyp/xcodeproj_file.py, tools/pretty_gyp.py
`python -m flake8 . --select F841`
=> chore: remove unused variables

pylib/gyp/generator/make.py, pylib/gyp/generator/msvs.py, pylib/gyp/generator/ninja.py, pylib/gyp/generator/xcode.py, pylib/gyp/xcode_emulation.py
`python -m flake8 . --select E231`
Refs: https://github.com/psf/black/issues/1288
=> chore: remove trailing commas

pylib/gyp/generator/make.py
Closes: https://github.com/nodejs/gyp-next/issues/28
Refs: https://github.com/nodejs/node/commit/50317c38a4511914e5eb69d6f05f290087887cf7#diff-50366fa1de3b4a645c172ab704f9155a
=> fix: upstream 50317c3 from nodejs/node

AUTHORS, setup.py
Now we have https://pypi.org/project/gyp-next/0.1/
/cc @targos @cclauss
=> meta: update setup.py for pypi

pylib/gyp/common.py
Refs: https://chromium.googlesource.com/external/gyp/+/ab4aca868d68b9de9b20a9991bbbb5e78ab48a30%5E!
Refs: https://github.com/nodejs/node/pull/32698#discussion_r405540105
/cc @targos @cclauss
=> fix windows bug

LICENSE
=> meta: relicense to gyp-next contributors

.github/workflows/Python_tests.yml
https://github.com/actions/checkout/releases
https://github.com/actions/setup-python/releases
=> Python_tests.yml: Upgrade Actions

CHANGELOG.md, setup.py
All notable changes to this project will be documented in this file.
The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
- Added support for MSVC cross-compilation. This allows compilation on x64 for
a Windows ARM target.
- Fixed XCode CLT version detection on macOS Catalina.
- Relicensed to Node.js contributors.
- Fixed Windows bug introduced in v0.2.0.
This is the first release of this project, based on https://chromium.googlesource.com/external/gyp with changes made over the
years in Node.js and node-gyp.
[Unreleased]: https://github.com/nodejs/gyp-next/compare/v0.3.0...HEAD
[0.3.0]: https://github.com/nodejs/gyp-next/compare/v0.2.1...v0.3.0
[0.2.1]: https://github.com/nodejs/gyp-next/compare/v0.2.0...v0.2.1
[0.2.0]: …
=> chore(release): v0.3.0

pylib/gyp/generator/ninja.py
This commit is a follow-up to a PR from the original Node repo.
https://github.com/nodejs/node/pull/33813#pullrequestreview-427320039
=> misc: replace 'whitelist' with 'allow'.

README.md
Acknowledge https://pypi.org/project/gyp-next
=> README.md: gyp-next is release to the Python Packaging_Index

pylib/gyp/generator/android.py, pylib/gyp/generator/msvs.py, pylib/gyp/generator/ninja.py, pylib/gyp/generator/xcode.py, pylib/gyp/input.py, pylib/gyp/xcode_emulation.py, pylib/gyp/xcodeproj_file.py, tools/pretty_vcproj.py
https://github.com/codespell-project/codespell
=> Fix typos discovered by codespell

README.md
A cleaner look for https://pypi.org/project/gyp-next
=> README.md: Better format for our next PyPI release

.github/workflows/Python_tests.yml
https://www.python.org/download/pre-releases/
=> GitHub Actions: Test Python 3.9 release candidate 1

.github/workflows/Python_tests.yml
https://www.python.org/downloads/release/python-390/
=> GitHub Actions: Python 3.9 is released

.github/workflows/node-gyp.yml
https://github.com/actions/setup-node/releases
=> ci: update actions/setup-node to v2

.github/workflows/Python_tests.yml, .github/workflows/node-gyp.yml
nodejs/node-gyp#2504 --> nodejs/node#40296
=> test: Add Python 3.10 to GitHub Actions

tools/pretty_gyp.py
I don't think there are any tests for this but I did some command-line
tests and, at least for the things I tested, this preserves the code
behavior while avoiding backtracking issues in the regular expression.
Closes: https://github.com/nodejs/gyp-next/issues/135
=> chore: refactor regular expression

.github/workflows/Python_tests.yml, .github/workflows/node-gyp.yml
https://github.com/actions/setup-node/releases
https://github.com/actions/setup-python/releases
Like nodejs/node-gyp#2623
=> test: Update GitHub Actions

.github/workflows/Python_tests.yml, .github/workflows/node-gyp.yml, .github/workflows/nodejs-windows.yml
https://github.com/actions/checkout/releases
=> Upgrade GitHub Actions

.github/workflows/release-please.yml
Hopefully it will work better, see https://github.com/nodejs/gyp-next/pull/167
=> chore: update release-please action

.github/workflows/python_tests.yml, pyproject.toml
=> GitHub Actions: Test on Python 3.11 production release

pylib/gyp/MSVSProject.py, pylib/gyp/generator/analyzer.py, pylib/gyp/generator/compile_commands_json.py, pylib/gyp/generator/msvs.py, pyproject.toml, tools/pretty_sln.py, tools/pretty_vcproj.py
https://beta.ruff.rs/docs/rules/#flake8-comprehensions-c4
% `ruff --select=C4 --statistics .`
```
8	C408	[*] Unnecessary `dict` call (rewrite as a literal)
5	C416	[*] Unnecessary `list` comprehension (rewrite using `list()`)
```
% `ruff --select=C4 --fix .`
```
Found 13 errors (13 fixed, 0 remaining).
```
=> chore: Use Python dict and list comprehensions

.github/dependabot.yml
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> chore(main): Keep GitHub Actions up to date with Dependabot

pylib/gyp/MSVSSettings.py
Refs: https://github.com/nodejs/node/pull/52870
=> feat: support language standard keys in msvs_settings

.github/workflows/node-gyp.yml, .github/workflows/nodejs.yml, .github/workflows/python_tests.yml, .github/workflows/release-please.yml
https://github.com/astral-sh/ruff-action?tab=readme-ov-file#readme
https://github.com/pypa/build?tab=readme-ov-file#integration-with-other-tools
Like
* nodejs/node-gyp#3114
=> chore: Use astral-sh/ruff-action@v3 to run the Python linter

README.md, pylib/gyp/__init__.py
% `uvx --from=gyp-next gyp --help`
```diff
- usage: usage: gyp [options ...] [build_file ...]
+ usage: gyp [options ...] [build_file ...]
```
=> fix(cli): remove duplicate usage
